apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: sporelets.sporelet.ai
spec:
  group: sporelet.ai
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                snapshot:
                  type: string
            status:
              type: object
              properties:
                phase:
                  type: string
                snapshot:
                  type: string
                conditions:
                  type: array
                  items:
                    type: object
                    properties:
                      type:
                        type: string
                      status:
                        type: string
                      reason:
                        type: string
                      message:
                        type: string
  scope: Namespaced
  names:
    plural: sporelets
    singular: sporelet
    kind: Sporelet
    shortNames:
      - sp
