name: Build and Publish Images

on:
  push:
    branches: [main]
    paths:
      - 'apps/operator/**'
      - 'apps/sporectl/**'
      - '.github/workflows/images.yml'

jobs:
  operator-image:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v5
        with:
          context: .
          file: apps/operator/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}/operator:${{ github.sha }}

  sporectl-image:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
    needs: operator-image
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v5
        with:
          context: .
          file: apps/sporectl/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}/sporectl:${{ github.sha }}
